"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 00:17:10.412386
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("budget_limit", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "projects",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "UPLOADING",
                "UPLOADED",
                "ANALYZING",
                "READY",
                "GENERATING",
                "COMPLETED",
                "FAILED",
                name="projectstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("current_analysis_id", sa.Uuid(), nullable=True),
        sa.Column("duplicated_from_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "source_videos",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_UPLOAD",
                "UPLOADED",
                "INGESTING",
                "READY",
                "REJECTED",
                "DELETED",
                name="sourcevideostatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "technical",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("proxy_key", sa.String(length=512), nullable=True),
        sa.Column("poster_key", sa.String(length=512), nullable=True),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("upload_id", sa.String(length=255), nullable=True),
        sa.Column("upload_part_size", sa.Integer(), nullable=True),
        sa.Column("upload_part_count", sa.Integer(), nullable=True),
        sa.Column("rights_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rights_statement", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_source_videos_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_videos")),
    )
    op.create_index(
        op.f("ix_source_videos_content_hash"), "source_videos", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_source_videos_project_id"), "source_videos", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_videos_upload_id"), "source_videos", ["upload_id"], unique=False
    )
    op.create_table(
        "video_analyses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_video_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="analysisstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column("mock", sa.Boolean(), nullable=False),
        sa.Column("dna_schema_version", sa.String(length=16), nullable=True),
        sa.Column(
            "dna",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("reused_from_id", sa.Uuid(), nullable=True),
        sa.Column("low_confidence_count", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_video_analyses_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
            name=op.f("fk_video_analyses_source_video_id_source_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_analyses")),
    )
    op.create_index(
        op.f("ix_video_analyses_project_id"), "video_analyses", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_video_analyses_source_video_id"),
        "video_analyses",
        ["source_video_id"],
        unique=False,
    )
    op.create_table(
        "actions",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("verb", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("actor_key", sa.String(length=64), nullable=True),
        sa.Column(
            "target_keys",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "shot_keys",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("essential", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_actions_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
        sa.UniqueConstraint("analysis_id", "key", name=op.f("uq_actions_analysis_id")),
    )
    op.create_index(op.f("ix_actions_analysis_id"), "actions", ["analysis_id"], unique=False)
    op.create_table(
        "edit_operations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("entity_key", sa.String(length=64), nullable=True),
        sa.Column(
            "op",
            sa.Enum(
                "SET_ATTRIBUTE",
                "CHANGE_APPEARANCE",
                "REPLACE",
                "REMOVE",
                "KEEP",
                "APPLY_PRESET",
                "ADD_ENTITY",
                "CORRECT",
                "INSTRUCTION",
                name="editoptype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("property", sa.String(length=128), nullable=True),
        sa.Column(
            "previous_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "new_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("instruction", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("manual", "suggestion", "ai", name="editsource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("suggestion_id", sa.Uuid(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "ACTIVE", "UNDONE", "DISCARDED", name="editstate", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "impact",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_edit_operations_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_edit_operations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_edit_operations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edit_operations")),
        sa.UniqueConstraint("project_id", "sequence", name=op.f("uq_edit_operations_project_id")),
    )
    op.create_index(
        op.f("ix_edit_operations_analysis_id"), "edit_operations", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_edit_operations_project_id"), "edit_operations", ["project_id"], unique=False
    )
    op.create_index(
        "ix_edit_operations_project_state", "edit_operations", ["project_id", "state"], unique=False
    )
    op.create_table(
        "generation_plans",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "EXECUTING",
                "EXECUTED",
                "FAILED",
                name="planstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "quality_mode",
            sa.Enum("ECONOMY", "BALANCED", "MAX", name="qualitymode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "render_kind",
            sa.Enum("preview", "final", name="renderkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("ops_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "plan",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expected_duration_sec", sa.Float(), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_generation_plans_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_generation_plans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_plans")),
    )
    op.create_index(
        op.f("ix_generation_plans_analysis_id"), "generation_plans", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_plans_project_id"), "generation_plans", ["project_id"], unique=False
    )
    op.create_table(
        "project_versions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column(
            "operations",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("output_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_project_versions_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_versions")),
        sa.UniqueConstraint("project_id", "number", name=op.f("uq_project_versions_project_id")),
    )
    op.create_index(
        op.f("ix_project_versions_analysis_id"), "project_versions", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_versions_project_id"), "project_versions", ["project_id"], unique=False
    )
    op.create_table(
        "relationships",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("scene_key", sa.String(length=64), nullable=True),
        sa.Column("subject_key", sa.String(length=64), nullable=False),
        sa.Column("predicate", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=64), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=True),
        sa.Column("end_time", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_relationships_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
        sa.UniqueConstraint("analysis_id", "key", name=op.f("uq_relationships_analysis_id")),
    )
    op.create_index(
        op.f("ix_relationships_analysis_id"), "relationships", ["analysis_id"], unique=False
    )
    op.create_table(
        "scenes",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("environment_key", sa.String(length=64), nullable=True),
        sa.Column(
            "graph",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_scenes_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenes")),
        sa.UniqueConstraint("analysis_id", "key", name=op.f("uq_scenes_analysis_id")),
    )
    op.create_index(op.f("ix_scenes_analysis_id"), "scenes", ["analysis_id"], unique=False)
    op.create_table(
        "suggestions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("entity_key", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "op",
            sa.Enum(
                "SET_ATTRIBUTE",
                "CHANGE_APPEARANCE",
                "REPLACE",
                "REMOVE",
                "KEEP",
                "APPLY_PRESET",
                "ADD_ENTITY",
                "CORRECT",
                "INSTRUCTION",
                name="editoptype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("property", sa.String(length=128), nullable=True),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("preview_key", sa.String(length=512), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_suggestions_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_suggestions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggestions")),
    )
    op.create_index(
        op.f("ix_suggestions_analysis_id"), "suggestions", ["analysis_id"], unique=False
    )
    op.create_index(
        "ix_suggestions_lookup",
        "suggestions",
        ["analysis_id", "entity_key", "category", "context_hash", "page"],
        unique=False,
    )
    op.create_index(op.f("ix_suggestions_project_id"), "suggestions", ["project_id"], unique=False)
    op.create_table(
        "entities",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "character",
                "hair",
                "wardrobe",
                "accessory",
                "object",
                "furniture",
                "environment",
                "environment_part",
                "lighting",
                "text",
                "audio",
                name="entitytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("subtype", sa.String(length=64), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_key", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "importance",
            sa.Enum(
                "ESSENTIAL",
                "IMPORTANT",
                "DECORATIVE",
                name="importance",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("editable", sa.Boolean(), nullable=False),
        sa.Column("replaceable", sa.Boolean(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_entities_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_entities_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_entities_scene_id_scenes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint("analysis_id", "key", name=op.f("uq_entities_analysis_id")),
    )
    op.create_index(op.f("ix_entities_analysis_id"), "entities", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_entities_project_id"), "entities", ["project_id"], unique=False)
    op.create_index("ix_entities_project_type", "entities", ["project_id", "type"], unique=False)
    op.create_index(op.f("ix_entities_scene_id"), "entities", ["scene_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "INGEST",
                "ANALYSIS",
                "PREVIEW",
                "GENERATION",
                name="jobkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PREPARING",
                "ANALYZING",
                "GENERATING",
                "QA",
                "REPAIRING",
                "ASSEMBLING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["generation_plans.id"],
            name=op.f("fk_jobs_plan_id_generation_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_jobs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_jobs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("project_id", "kind", "idempotency_key", name="uq_jobs_idempotency"),
    )
    op.create_index(op.f("ix_jobs_plan_id"), "jobs", ["plan_id"], unique=False)
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_index("ix_jobs_project_status", "jobs", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
    op.create_table(
        "shots",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("transition_in", sa.String(length=16), nullable=False),
        sa.Column(
            "camera",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "lighting",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "dominant_colors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "keyframes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("thumbnail_key", sa.String(length=512), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_shots_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["scenes.id"], name=op.f("fk_shots_scene_id_scenes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shots")),
        sa.UniqueConstraint("analysis_id", "key", name=op.f("uq_shots_analysis_id")),
    )
    op.create_index(op.f("ix_shots_analysis_id"), "shots", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_shots_scene_id"), "shots", ["scene_id"], unique=False)
    op.create_table(
        "entity_tracks",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("entity_key", sa.String(length=64), nullable=False),
        sa.Column("shot_key", sa.String(length=64), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column(
            "samples",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["video_analyses.id"],
            name=op.f("fk_entity_tracks_analysis_id_video_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_entity_tracks_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_tracks")),
        sa.UniqueConstraint("analysis_id", "key", name=op.f("uq_entity_tracks_analysis_id")),
    )
    op.create_index(
        op.f("ix_entity_tracks_analysis_id"), "entity_tracks", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_entity_tracks_entity_id"), "entity_tracks", ["entity_id"], unique=False
    )
    op.create_table(
        "generation_outputs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "FINAL",
                "PREVIEW",
                "SHOT_SEGMENT",
                "IMAGE_PREVIEW",
                "REFERENCE_IMAGE",
                "PROVENANCE",
                name="outputkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("shot_key", sa.String(length=64), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("duration_sec", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column(
            "provenance",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_generation_outputs_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_generation_outputs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_outputs")),
    )
    op.create_index(
        op.f("ix_generation_outputs_job_id"), "generation_outputs", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_generation_outputs_project_id"), "generation_outputs", ["project_id"], unique=False
    )
    op.create_table(
        "job_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint("job_id", "seq", name=op.f("uq_job_events_job_id")),
    )
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    op.create_table(
        "provider_usage",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILURE", name="usagestatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("actual_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Float(), nullable=True),
        sa.Column("seconds_generated", sa.Float(), nullable=True),
        sa.Column("shot_key", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_provider_usage_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_provider_usage_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_provider_usage_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_usage")),
    )
    op.create_index(
        op.f("ix_provider_usage_created_at"), "provider_usage", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_provider_usage_job_id"), "provider_usage", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_provider_usage_project_id"), "provider_usage", ["project_id"], unique=False
    )
    op.create_index(
        "ix_provider_usage_provider_capability",
        "provider_usage",
        ["provider", "capability"],
        unique=False,
    )
    op.create_index(op.f("ix_provider_usage_user_id"), "provider_usage", ["user_id"], unique=False)
    op.create_table(
        "qa_reports",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("shot_key", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "checks",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_qa_reports_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_qa_reports_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_reports")),
    )
    op.create_index(op.f("ix_qa_reports_job_id"), "qa_reports", ["job_id"], unique=False)
    op.create_index(op.f("ix_qa_reports_project_id"), "qa_reports", ["project_id"], unique=False)
    op.create_table(
        "cost_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("provider_usage_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("ESTIMATE", "ACTUAL", name="costkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("seconds_generated", sa.Float(), nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Float(), nullable=True),
        sa.Column("shot_key", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_cost_entries_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["generation_plans.id"],
            name=op.f("fk_cost_entries_plan_id_generation_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_cost_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_usage_id"],
            ["provider_usage.id"],
            name=op.f("fk_cost_entries_provider_usage_id_provider_usage"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cost_entries_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_entries")),
    )
    op.create_index(op.f("ix_cost_entries_job_id"), "cost_entries", ["job_id"], unique=False)
    op.create_index(op.f("ix_cost_entries_plan_id"), "cost_entries", ["plan_id"], unique=False)
    op.create_index(
        op.f("ix_cost_entries_project_id"), "cost_entries", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_cost_entries_provider_usage_id"),
        "cost_entries",
        ["provider_usage_id"],
        unique=False,
    )
    op.create_index(op.f("ix_cost_entries_user_id"), "cost_entries", ["user_id"], unique=False)
    op.create_table(
        "qa_issues",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("shot_key", sa.String(length=64), nullable=False),
        sa.Column(
            "issue_type",
            sa.Enum(
                "ENTITY_DISAPPEARED",
                "ENTITY_DUPLICATED",
                "WARDROBE_CHANGED",
                "FACE_CHANGED",
                "FLICKERING",
                "ANATOMY",
                "BACKGROUND_DRIFT",
                "INTERPENETRATION",
                "UNREQUESTED_CHANGE",
                "ACTION_MISMATCH",
                "CAMERA_MISMATCH",
                "DURATION_MISMATCH",
                "RESOLUTION_MISMATCH",
                "BLACK_FRAMES",
                "ARTIFACTS",
                name="qaissuetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW", "MEDIUM", "HIGH", "CRITICAL", name="qaseverity", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_entity_key", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "REPAIRED",
                "UNRESOLVED",
                "ACCEPTED",
                name="qaissuestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("repair_attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_qa_issues_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_qa_issues_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["qa_reports.id"],
            name=op.f("fk_qa_issues_report_id_qa_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_issues")),
    )
    op.create_index(op.f("ix_qa_issues_job_id"), "qa_issues", ["job_id"], unique=False)
    op.create_index(op.f("ix_qa_issues_project_id"), "qa_issues", ["project_id"], unique=False)
    op.create_index(op.f("ix_qa_issues_report_id"), "qa_issues", ["report_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qa_issues_report_id"), table_name="qa_issues")
    op.drop_index(op.f("ix_qa_issues_project_id"), table_name="qa_issues")
    op.drop_index(op.f("ix_qa_issues_job_id"), table_name="qa_issues")
    op.drop_table("qa_issues")
    op.drop_index(op.f("ix_cost_entries_user_id"), table_name="cost_entries")
    op.drop_index(op.f("ix_cost_entries_provider_usage_id"), table_name="cost_entries")
    op.drop_index(op.f("ix_cost_entries_project_id"), table_name="cost_entries")
    op.drop_index(op.f("ix_cost_entries_plan_id"), table_name="cost_entries")
    op.drop_index(op.f("ix_cost_entries_job_id"), table_name="cost_entries")
    op.drop_table("cost_entries")
    op.drop_index(op.f("ix_qa_reports_project_id"), table_name="qa_reports")
    op.drop_index(op.f("ix_qa_reports_job_id"), table_name="qa_reports")
    op.drop_table("qa_reports")
    op.drop_index(op.f("ix_provider_usage_user_id"), table_name="provider_usage")
    op.drop_index("ix_provider_usage_provider_capability", table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_project_id"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_job_id"), table_name="provider_usage")
    op.drop_index(op.f("ix_provider_usage_created_at"), table_name="provider_usage")
    op.drop_table("provider_usage")
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_generation_outputs_project_id"), table_name="generation_outputs")
    op.drop_index(op.f("ix_generation_outputs_job_id"), table_name="generation_outputs")
    op.drop_table("generation_outputs")
    op.drop_index(op.f("ix_entity_tracks_entity_id"), table_name="entity_tracks")
    op.drop_index(op.f("ix_entity_tracks_analysis_id"), table_name="entity_tracks")
    op.drop_table("entity_tracks")
    op.drop_index(op.f("ix_shots_scene_id"), table_name="shots")
    op.drop_index(op.f("ix_shots_analysis_id"), table_name="shots")
    op.drop_table("shots")
    op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
    op.drop_index("ix_jobs_project_status", table_name="jobs")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_plan_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_entities_scene_id"), table_name="entities")
    op.drop_index("ix_entities_project_type", table_name="entities")
    op.drop_index(op.f("ix_entities_project_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_analysis_id"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_suggestions_project_id"), table_name="suggestions")
    op.drop_index("ix_suggestions_lookup", table_name="suggestions")
    op.drop_index(op.f("ix_suggestions_analysis_id"), table_name="suggestions")
    op.drop_table("suggestions")
    op.drop_index(op.f("ix_scenes_analysis_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_relationships_analysis_id"), table_name="relationships")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_project_versions_project_id"), table_name="project_versions")
    op.drop_index(op.f("ix_project_versions_analysis_id"), table_name="project_versions")
    op.drop_table("project_versions")
    op.drop_index(op.f("ix_generation_plans_project_id"), table_name="generation_plans")
    op.drop_index(op.f("ix_generation_plans_analysis_id"), table_name="generation_plans")
    op.drop_table("generation_plans")
    op.drop_index("ix_edit_operations_project_state", table_name="edit_operations")
    op.drop_index(op.f("ix_edit_operations_project_id"), table_name="edit_operations")
    op.drop_index(op.f("ix_edit_operations_analysis_id"), table_name="edit_operations")
    op.drop_table("edit_operations")
    op.drop_index(op.f("ix_actions_analysis_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_video_analyses_source_video_id"), table_name="video_analyses")
    op.drop_index(op.f("ix_video_analyses_project_id"), table_name="video_analyses")
    op.drop_table("video_analyses")
    op.drop_index(op.f("ix_source_videos_upload_id"), table_name="source_videos")
    op.drop_index(op.f("ix_source_videos_project_id"), table_name="source_videos")
    op.drop_index(op.f("ix_source_videos_content_hash"), table_name="source_videos")
    op.drop_table("source_videos")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###
